GuildCars/GuildCars.UI/Controllers/InventoryController.cs
using GuildCars.Data.Factories;
using GuildCars.Models.Queries;
using GuildCars.Models.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class InventoryController : Controller
    {
        public List<VehicleDetail> vehicles { get; set; }

        public ActionResult New()
        {
            vehicles = VehicleRepositoryFactory.GetRepository().GetByNewOrUsed(true);
            return View(vehicles);
        }

        public ActionResult Used()
        {
            vehicles = VehicleRepositoryFactory.GetRepository().GetByNewOrUsed(false);
            return View(vehicles);
        }

        [HttpGet]
        public ActionResult Details(string vin)
        {
            return View(VehicleRepositoryFactory.GetRepository().GetDetailByID(vin));
        }
    }
}

GuildCars/GuildCars.UI/Controllers/SalesController.cs
using GuildCars.Data.Factories;
using GuildCars.Models.Queries;
using GuildCars.Models.ViewModels;
using GuildCars.UI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class SalesController : Controller
    {

        public List<VehicleDetail> vehicles { get; set; }

        [HttpGet]
        public ActionResult Index()
        {
            //code to get user id from usermanager. Useful, but i really need the role moreso
            if (Request.IsAuthenticated)
            {
                var userMgr = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = userMgr.FindByName(User.Identity.Name);
                ViewBag.UserId = user.Id;
            }

            vehicles = VehicleRepositoryFactory.GetRepository().GetByNewOrUsed(true);
            vehicles.AddRange(VehicleRepositoryFactory.GetRepository().GetByNewOrUsed(false));
            return View(vehicles);
        }

        [HttpGet]
        public ActionResult Purchase(string vin)
        {
            VehiclePurchaseDetailVM model = new VehiclePurchaseDetailVM();
            model.VehicleDetail = VehicleRepositoryFactory.GetRepository().GetDetailByID(vin);
            model.Vehicle = VehicleRepositoryFactory.GetRepository().GetByID(vin);
            return View(model);
        }

    }
}

GuildCars/GuildCars.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        @Html.ActionLink("GuildCars", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item nav-link @("Index" == "Index" ? "active" : "")">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="nav-link active">@Html.ActionLink("New Inventory", "New", "Inventory")</li>
                <li class="nav-link">@Html.ActionLink("Used Inventory", "Used", "Inventory")</li>
                <li class="nav-link">@Html.ActionLink("Specials", "Specials", "Home")</li>
                <li class="nav-link">@Html.ActionLink("Contact", "Contact", "Home")</li>
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GuildCars/GuildCars.UI/Views/Shared/_VehicleDetailPartial.cshtml
@{string pageTitle = ViewBag.Title; }
    <div class="row border rounded"  style="margin-bottom:10px">
        <div class="col-xs-12 col-sm-12 col-md-3">
            <h4>@Model.ModelYear @Model.ModelName @Model.MakeName </h4>
            <p><img src="@Url.Content("~/images/" + Model.ImageFileName)" /></p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-9">
            <table>
                <tbody>
                    <tr>
                        <td><strong>Body  Style: </strong></td>
                        <td>@Model.BodyTypeName</td>
                        <td><strong>Interior: </strong></td>
                        <td>@Model.InteriorColorName</td>
                        <td><strong>Sale Price: </strong></td>
                        <td>$@Model.SalePrice</td>
                    </tr>
                    <tr>
                        <td><strong>Manual: </strong></td>
                        <td>@Model.IsManual</td>
                        <td><strong>Mileage: </strong></td>
                        <td>@Model.Mileage</td>
                        <td><strong>MSRP: </strong></td>
                        <td>$@Model.RetailPrice</td>
                    </tr>
                    <tr>
                        <td><strong>Color: </strong></td>
                        <td>@Model.ExteriorColorName</td>
                        <td><strong>VIN #: </strong></td>
                        <td>@Model.VIN</td>
                    </tr>
                    @{ if (pageTitle.Contains("Details"))
                        {
                            <tr>
                                <td><strong>Description: </strong></td>
                                <td>@Model.VehicleDesc</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @{ switch (pageTitle)
                {
                    case "Inventory Used Results":
                    //fall through
                    case "Inventory New Results":
                        @Html.ActionLink("Details", "Details", "Inventory", new { vin = Model.VIN }, new { @class = "btn btn-outline-secondary float-right mt-auto" })
                        break;
                    case "Inventory Details":
                        @Html.ActionLink("Contact", "Contact", "Home", new { vin = Model.VIN }, new { @class = "btn btn-outline-secondary float-right" })
                        break;
                    case "Sales Inventory Results":
                        if (Request.IsAuthenticated) {@Html.ActionLink("Purchase", "Purchase", "Sales", new { vin = Model.VIN }, new { @class = "btn btn-outline-secondary float-right align-baseline" })}
                        break;
                    case "Admin Inventory Results":
                        if (Request.IsAuthenticated) {@Html.ActionLink("Edit", "EditVehicle", "Admin", new { vin = Model.VIN }, new { @class = "btn btn-outline-secondary float-right align-baseline" })}
                        break;
                    case "Purchase Details":
                        //Nothing here
                        break;
                }
            }
        </div>
    </div>

GuildCars/GuildCars.UI/Views/Shared/_VehicleSearchPartial.cshtml
<div class="col-12 mw-100 d-inline-block border border-primary p-3 text-secondary" style="margin-top:10px">
    <h5>Quick Search</h5>
    <form class="form-group form-inline row">
        <div class="col-md-4">
            <label class="sr-only" for="quickSearchTextbox">Quick Search</label>
            <input type="text" class="form-control mb-2 mr-sm-2" id="quickSearchTextbox" placeholder="Enter make, model, or year">
        </div>

        <div class="col-md-4 form-group">
            <label for="Price" class="form-inline">Price </label>
            <input type="text" class="form-control mb-2 mr-sm-2 w-25" id="minPrice" placeholder="No Min">
            <input type="text" class="form-control mb-2 mr-sm-2 w-25" id="maxPrice" placeholder="No Max">
        </div>
        <div class="col-md-4 form-group">
            <label for="Year">Year </label>
            <input type="text" class="form-control mb-2 mr-sm-2 w-25" id="minYear" placeholder="No Min">
            <input type="text" class="form-control mb-2 mr-sm-2 w-25" id="maxYear" placeholder="No Max">
        </div>
    </form>
    <button type="submit" onclick="search()" class="btn btn-outline-primary">Search</button>
</div>